apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: socks-honeytrap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: socks-honeytrap
    spec:
      containers:
      - name: socks-honeytrap
        image: trustnetworks.azurecr.io/socks-honeytrap:0.1_1
        resources:
          requests:
            memory: "512M"
            cpu: "0.3"
          limits:
            memory: "512M"
            cpu: "0.5"
        ports:
        - containerPort: 1080
          name: proxy
